pesquisar_task:
  description: >
    Realizar uma pesquisa sobre o destino {destino}, trazendo detalhes sobre custo médio de diárias do hotel,
    avaliação geral de hotéis localizados em pontos seguros e estratégicos,
    além dos passeios turisticos e referências gastronomicas pertencentes à região do {destino}.
    Certifique-se de gerar o custo médio das opções gastronômicas e passeios.
    Se certifique sobre encontrar informações relevantes e atuais. O ano atual é 2025.
  expected_output: >
    Uma lista com pelo menos 5 hotéis, 5 restaurantes e 5 passeios para serem feitos no {destino}
  agent: pesquisador

criar_roteiro_task:
description: >
  Ler o relatório que recebeu e, com base no orçamento do cliente e nos valores do relatório do destino, criar um roteiro de viagem personalizado.
expected_output: >
  um roteiro com o hotel, 3 restaurantes a serem visitados e 3 passeios a serem feitos no destino, em formato markdown.O roteiro deve conter
  os preços médios de passeios e estadias.
  Lembre-se de selecionar opções que caibam no orçamentdo de R${budget}.
  Lembre-se que o orçamento será utilizado durante 5 dias.
agent: agente_viagem